const partidos = [
  // JORNADA 1
  {
    numero: 1,
    fase: "Grupos",
    grupo: "A",
    fecha: "11 Junio 2026",
    hora: "15:00",
    local: "México",
    visitante: "Sudáfrica",
    estadio: "Estadio Azteca",
    ciudad: "Ciudad de México",
    resultado: "2-0",
    estado: "Finalizado"
  },
  {
    numero: 2,
    fase: "Grupos",
    grupo: "A",
    fecha: "11 Junio 2026",
    hora: "22:00",
    local: "Corea del Sur",
    visitante: "Chequia",
    estadio: "Estadio Akron",
    ciudad: "Guadalajara",
    resultado: "2-1",
    estado: "Finalizado"
  },
  {
    numero: 3,
    fase: "Grupos",
    grupo: "B",
    fecha: "12 Junio 2026",
    hora: "15:00",
    local: "Canadá",
    visitante: "Bosnia y Herzegovina",
    estadio: "BMO Field",
    ciudad: "Toronto",
    resultado: "1-1",
    estado: "Finalizado"
  },
  {
    numero: 4,
    fase: "Grupos",
    grupo: "D",
    fecha: "12 Junio 2026",
    hora: "21:00",
    local: "Estados Unidos",
    visitante: "Paraguay",
    estadio: "SoFi Stadium",
    ciudad: "Los Ángeles",
    resultado: "4-1",
    estado: "Finalizado"
  },
  {
    numero: 5,
    fase: "Grupos",
    grupo: "B",
    fecha: "13 Junio 2026",
    hora: "18:00",
    local: "Catar",
    visitante: "Suiza",
    estadio: "Levi's Stadium",
    ciudad: "San Francisco",
    resultado: "1-1",
    estado: "Finalizado"
  },
  {
    numero: 6,
    fase: "Grupos",
    grupo: "C",
    fecha: "13 Junio 2026",
    hora: "18:00",
    local: "Brasil",
    visitante: "Marruecos",
    estadio: "MetLife Stadium",
    ciudad: "Nueva York/Nueva Jersey",
    resultado: "1-1",
    estado: "Finalizado"
  },
  {
    numero: 7,
    fase: "Grupos",
    grupo: "C",
    fecha: "13 Junio 2026",
    hora: "21:00",
    local: "Haití",
    visitante: "Escocia",
    estadio: "Gillette Stadium",
    ciudad: "Boston",
    resultado: "0-2",
    estado: "Finalizado"
  },
  {
    numero: 8,
    fase: "Grupos",
    grupo: "D",
    fecha: "13 Junio 2026",
    hora: "00:00",
    local: "Australia",
    visitante: "Turquía",
    estadio: "BC Place",
    ciudad: "Vancouver",
    resultado: "1-2",
    estado: "Finalizado"
  },
  {
    numero: 9,
    fase: "Grupos",
    grupo: "G",
    fecha: "14 Junio 2026",
    hora: "15:00",
    local: "Bélgica",
    visitante: "Egipto",
    estadio: "Lincoln Financial Field",
    ciudad: "Filadelfia",
    resultado: "3-1",
    estado: "Finalizado"
  },
  {
    numero: 10,
    fase: "Grupos",
    grupo: "G",
    fecha: "14 Junio 2026",
    hora: "18:00",
    local: "Irán",
    visitante: "Nueva Zelanda",
    estadio: "Arrowhead Stadium",
    ciudad: "Kansas City",
    resultado: "2-2",
    estado: "Finalizado"
  },
  {
    numero: 11,
    fase: "Grupos",
    grupo: "E",
    fecha: "15 Junio 2026",
    hora: "15:00",
    local: "Francia",
    visitante: "Senegal",
    estadio: "Mercedes-Benz Stadium",
    ciudad: "Atlanta",
    resultado: "3-1",
    estado: "Finalizado"
  },
  {
    numero: 12,
    fase: "Grupos",
    grupo: "E",
    fecha: "15 Junio 2026",
    hora: "18:00",
    local: "Irak",
    visitante: "Noruega",
    estadio: "NRG Stadium",
    ciudad: "Houston",
    resultado: "1-4",
    estado: "Finalizado"
  },
  {
    numero: 13,
    fase: "Grupos",
    grupo: "F",
    fecha: "15 Junio 2026",
    hora: "19:00",
    local: "Argentina",
    visitante: "Argelia",
    estadio: "Hard Rock Stadium",
    ciudad: "Miami",
    resultado: "3-0",
    estado: "Finalizado"
  },
  {
    numero: 14,
    fase: "Grupos",
    grupo: "F",
    fecha: "16 Junio 2026",
    hora: "13:00",
    local: "Austria",
    visitante: "Jordania",
    estadio: "Lumen Field",
    ciudad: "Seattle",
    resultado: "1-0",
    estado: "Finalizado"
  },
  {
    numero: 15,
    fase: "Grupos",
    grupo: "H",
    fecha: "16 Junio 2026",
    hora: "16:00",
    local: "Portugal",
    visitante: "RD del Congo",
    estadio: "Estadio BBVA",
    ciudad: "Monterrey",
    resultado: "2-0",
    estado: "Finalizado"
  },
  {
    numero: 16,
    fase: "Grupos",
    grupo: "H",
    fecha: "16 Junio 2026",
    hora: "19:00",
    local: "Inglaterra",
    visitante: "Croacia",
    estadio: "SoFi Stadium",
    ciudad: "Los Ángeles",
    resultado: "1-1",
    estado: "Finalizado"
  },

  // JORNADA 2 (PARTIDOS DE HOY Y PRÓXIMOS)
  {
    numero: 17,
    fase: "Grupos",
    grupo: "A",
    fecha: "17 Junio 2026",
    hora: "14:00",
    local: "México",
    visitante: "Chequia",
    estadio: "Estadio Azteca",
    ciudad: "Ciudad de México",
    resultado: "-",
    estado: "Próximo"
  },
  {
    numero: 18,
    fase: "Grupos",
    grupo: "A",
    fecha: "17 Junio 2026",
    hora: "17:00",
    local: "Sudáfrica",
    visitante: "Corea del Sur",
    estadio: "Estadio Akron",
    ciudad: "Guadalajara",
    resultado: "-",
    estado: "Próximo"
  },
  {
    numero: 19,
    fase: "Grupos",
    grupo: "B",
    fecha: "18 Junio 2026",
    hora: "15:00",
    local: "Canadá",
    visitante: "Suiza",
    estadio: "BC Place",
    ciudad: "Vancouver",
    resultado: "-",
    estado: "Próximo"
  },
  {
    numero: 20,
    fase: "Grupos",
    grupo: "B",
    fecha: "18 Junio 2026",
    hora: "18:00",
    local: "Bosnia y Herzegovina",
    visitante: "Catar",
    estadio: "BMO Field",
    ciudad: "Toronto",
    resultado: "-",
    estado: "Próximo"
  }
];
